name: Build and Upload

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 */30 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - run: ./gradlew build --stacktrace

      - uses: actions/upload-artifact@v3
        with:
          path: |
            enigma*/build/libs/*.jar

      - uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() }}
        with:
          reports: |
            enigma*/build/reports/checkstyle/*.xml